services:
  postgres:
    image: postgres:15-alpine
    container_name: medspa_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: medspa_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d medspa_local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgweb:
    image: sosedoff/pgweb
    container_name: medspa_pgweb
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://dev:dev@postgres:5432/medspa_local?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local